# Generated by Django 4.2.26 on 2026-10-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_coupon_order_coupon_code_order_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
